# Generated by Django 4.2.2 on 2023-06-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academica', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='pago',
            field=models.CharField(default='100', max_length=5),
        ),
    ]
